# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Best Practices for HPC Software Developers Webinar Series
author: IDEAS Productivity Project
email: IdeasProductivity@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Revamping the webinar site.  Very much a work in progress.
baseurl: "/hpc-best-practices-webinars" # the subpath of your site, e.g. /blog
url: "https://ideas-productivity.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  ideas-productivity
rss: rss

# URL for the official webinar site, where everything is archived
# Links for specific webinars are constructed from this URL by adding
# the appropriate anchor
hpcbp-url: https://ideas-productivity.org/events/hpc-best-practices-webinars/


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  
# By convention, we "operate" on US Eastern time
timezone: America/New_York

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# This is needed to generate output for future webinars
future: true

collections:
  webinars:
    output: true
# Symlink to webinars to generate code for ideas-productivity.org Wordpress site
  ipweb-entries:
    output: true
# Symlink to webinars to generate code for BSSw Events
  bssw-events:
    output: true
  presenters:
    output: true

defaults:
  - scope:
      path: ""
      type: "webinars"
    values:
      layout: "webinar"
  - scope:
      path: ""
      type: "ipweb-entries"
    values:
      layout: "ipweb-webinar"
  - scope:
      path: ""
      type: "bssw-events"
    values:
      layout: "bssw-event"
  - scope:
      path: ""
      type: "presenters"
    values:
      layout: "presenter"

# End of file
